// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Badge struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

type Course struct {
	ID           int64            `json:"id"`
	Title        string           `json:"title"`
	Description  string           `json:"description"`
	InstructorID int64            `json:"instructor_id"`
	Icon         string           `json:"icon"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Published    bool             `json:"published"`
	Available    bool             `json:"available"`
}

type Element struct {
	ID          int64       `json:"id"`
	SubmoduleID int64       `json:"submodule_id"`
	Type        string      `json:"type"`
	Content     string      `json:"content"`
	QuizID      pgtype.Int8 `json:"quiz_id"`
	Order       int32       `json:"order"`
}

type Module struct {
	ID          int64  `json:"id"`
	CourseID    int64  `json:"course_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Order       int32  `json:"order"`
}

type Quiz struct {
	ID           int64  `json:"id"`
	SubmoduleID  int64  `json:"submodule_id"`
	Question     string `json:"question"`
	QuestionType string `json:"question_type"`
	XpReward     int32  `json:"xp_reward"`
}

type QuizAnswer struct {
	ID         int64  `json:"id"`
	QuizID     int64  `json:"quiz_id"`
	AnswerText string `json:"answer_text"`
	IsCorrect  bool   `json:"is_correct"`
}

type Submodule struct {
	ID       int64  `json:"id"`
	ModuleID int64  `json:"module_id"`
	Title    string `json:"title"`
	XpReward int32  `json:"xp_reward"`
	Order    int32  `json:"order"`
}

type User struct {
	ID              int64            `json:"id"`
	Email           string           `json:"email"`
	FullName        string           `json:"full_name"`
	Password        string           `json:"password"`
	IsAdministrator bool             `json:"is_administrator"`
	IsInstructor    bool             `json:"is_instructor"`
	Xp              int32            `json:"xp"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type UserAnsweredQuiz struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	QuizID int64 `json:"quiz_id"`
}

type UserBadge struct {
	ID      int64 `json:"id"`
	UserID  int64 `json:"user_id"`
	BadgeID int64 `json:"badge_id"`
}

type UserCompletedSubmodule struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"user_id"`
	SubmoduleID int64            `json:"submodule_id"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type UserCourse struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	CourseID  int64 `json:"course_id"`
	Completed bool  `json:"completed"`
}
