name: Manifest scan

on:
  workflow_call:

jobs:
  polaris-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: azure/setup-helm@v4.2.0
      with:
        version: "v3.14.0"

    - name: Install Polaris
      run: |
        curl -L "https://github.com/FairwindsOps/polaris/releases/download/8.5.1/polaris_linux_amd64.tar.gz" > polaris.tar.gz
        tar -xvf polaris.tar.gz
        sudo mv polaris /usr/local/bin/

    - name: Render Helm templates
      run: |
        helm template ./helm/ > rendered-manifests.yaml

    - name: Run Polaris scan
      run: |
        polaris audit --audit-path ./rendered-manifests.yaml --format=pretty
